name: Source request
description: Request a new source
labels: [Source request]
body:

  - type: input
    id: name
    attributes:
      label: Source name
      placeholder: "Not Real Scans"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Source URL
      placeholder: "https://notrealscans.org"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Language
      placeholder: "English"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Additional information
      placeholder: |
        Content type (manga, manhwa, etc.)
        NSFW status
        Any other relevant details

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Prerequisites
      description: Please confirm these before submitting
      options:
        - label: I have checked that this source doesn't already exist in the [extension listing](https://keiyoushi.github.io/extensions/)
          required: true
        - label: I have searched existing issues and this is not a duplicate request
          required: true
        - label: The source is active and has sufficient content
          required: true